openapi: 3.0.0
info:
  title: 'Walnut API'
  contact:
    email: hello@clivern.com
  version: 0.1.0
paths:
  /:
    get:
      operationId: 'App\Controller\HealthController::index'
      responses:
        '200':
          description: 'Application is up'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '500':
          description: 'Application is down'
components:
  schemas:
    Health:
      properties:
        status:
          type: string
      type: object
